/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.jugador.domibo;

import javax.swing.*;
import java.awt.*;
import java.awt.dnd.*;
import java.awt.event.*;
import java.util.*;

/**
 *
 * @author Pc
 */
public class FormularioDelTablero extends javax.swing.JFrame {
    private java.util.List<JFicha> listaFichas;
    private Controlador controlador;
    
    /**
     * Creates new form FormularioDelTablero
     */
    public FormularioDelTablero() {
        initComponents();
        setTitle("DomiBO");
        setLocationRelativeTo(null);
        
        fichasPanel.setBackground(Color.DARK_GRAY);
        fichasPanel.setLayout(new FlowLayout());
        
        dropPanel.setBackground(Color.LIGHT_GRAY);
        dropPanel.setLayout(new FlowLayout());
        listaFichas = new ArrayList<>();
        generateFichas(4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fichasPanel = new javax.swing.JPanel();
        dropPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 51));

        javax.swing.GroupLayout fichasPanelLayout = new javax.swing.GroupLayout(fichasPanel);
        fichasPanel.setLayout(fichasPanelLayout);
        fichasPanelLayout.setHorizontalGroup(
            fichasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 885, Short.MAX_VALUE)
        );
        fichasPanelLayout.setVerticalGroup(
            fichasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dropPanelLayout = new javax.swing.GroupLayout(dropPanel);
        dropPanel.setLayout(dropPanelLayout);
        dropPanelLayout.setHorizontalGroup(
            dropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dropPanelLayout.setVerticalGroup(
            dropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fichasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dropPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(dropPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fichasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateFichas(int n) {
        Random random = new Random();
        for (int i = 0; i < n; i++) {
            int puntosIzquierda = random.nextInt(7);
            int puntosDerecha = random.nextInt(7);
            JFicha ficha = new JFicha(3, 3);
            fichasPanel.add(ficha);
            listaFichas.add(ficha);

            ficha.setTransferHandler(new ValueExportTransferHandler(ficha));
            ficha.addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent e) {
                    JComponent comp = (JComponent) e.getSource();
                    TransferHandler handler = comp.getTransferHandler();
                    handler.exportAsDrag(comp, e, TransferHandler.MOVE);
                }
            });
        }
        fichasPanel.revalidate();
        fichasPanel.repaint();
    }
    
    public void asignarControlador(Controlador controlador){
        this.controlador=controlador;
        new DropTarget(dropPanel, new FichaDropTargetListener(fichasPanel, dropPanel, listaFichas,controlador));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioDelTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioDelTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioDelTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioDelTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioDelTablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dropPanel;
    private javax.swing.JPanel fichasPanel;
    // End of variables declaration//GEN-END:variables

    public JFicha obetenerFicha(String sentido) {
        if(sentido=="izquierda"){
            return (JFicha) dropPanel.getComponent(1);
        }else{
            int count = dropPanel.getComponentCount();
            return (JFicha) dropPanel.getComponent(count - 2);
        }
    }

    public void addFicha(JFicha ficha) {
        System.out.println("LLEGO A AGREGAR FICHA FORMULARIO");
        System.out.println("FICHA QUE LLEGA: "+ficha.toString());
        dropPanel.add(ficha);
        dropPanel.revalidate();
        dropPanel.repaint();
    }
}
